arm_id:                           $(arg arm_id)
singularity_warning_threshold:    0.0001               # print a warning if the smallest singular value of J x J^T drops below this value (use -1 to disable)

franka_gripper:
  type:    franka_gazebo/FrankaGripperSim
  arm_id:  $(arg arm_id)

  finger1:
    gains: { p: 100, i: 0, d: 1.0 }

  finger2:
    gains: { p: 100, i: 0, d: 1.0 }
